### ISSUE TITLE
[BUG] Client gets error 400 Bad request on attempting to update research profile

### ISSUE THREAD

**Issue by mdryankov** [rokwire/core-building-block#651] opened 2023-04-04 15:01 UTC
**Describe the bug**
Client gets error 400 Bad request on PUT https://api-dev.rokwire.illinois.edu/core/services/account/profile

PUT https://api-dev.rokwire.illinois.edu/core/services/account/profile

Body:
{"id":"7a41837f-52a9-11ec-b2c3-0a58a9feac02","first_name":"Mladen","middle_name":null,"last_name":"Dryankov","birth_year":0,"photo_url":"","email":"dryankov@illinois.edu","phone":"","address":"","state":"","zip_code":"","country":"","unstructured_properties":{"research_questionnaire_answers":{"demographics":{"q01":["a03"],"q04":["a01"],"q03":["a01"],"q02":["a01"],"q05":["a01"],"q06":["a01"],"q07":["a01"],"q08":["a01"]}}}}

**To Reproduce**
Try to update research profile trough UIUC client

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shurwit** [comment] 2023-04-04 15:08
Thanks @mdryankov, this is a duplicate of #641. I will review and merge the associated PR and redploy.

**Closed by shurwit** 2023-04-04 15:08 UTC
Labels: bug
